//! # Trident Generated Types
//!
//! This file is automatically generated by Trident.
//! **DO NOT EDIT THIS FILE MANUALLY**

#![allow(dead_code)]
#![allow(unused_imports)]

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use trident_fuzz::fuzzing::*;

// ============================================================================
// PROGRAM MODULES
// ============================================================================

// ----------------------------------------------------------------------------
// Program: transfer_hook
// ----------------------------------------------------------------------------
pub mod transfer_hook {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for transfer_hook
    pub fn program_id() -> Pubkey {
        pubkey!("F8wwXWp8JUKVrDPwFCpG2NrheV3X7KKatoDuiYeBigkf")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: InitializeExtraAccountMetaList
    // ....................................................................

    /// Main instruction struct for InitializeExtraAccountMetaList
    pub struct InitializeExtraAccountMetaListInstruction {
        pub accounts: InitializeExtraAccountMetaListInstructionAccountMetas,
        pub data: InitializeExtraAccountMetaListInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for InitializeExtraAccountMetaList instruction
    #[derive(Debug, Clone, Default)]
    pub struct InitializeExtraAccountMetaListInstructionAccountMetas {
        pub payer: AccountMeta,

        pub extra_account_meta_list: AccountMeta,

        pub mint: AccountMeta,

        pub sss_token_program: AccountMeta,

        pub roles_config: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for InitializeExtraAccountMetaList instruction
    #[derive(Debug, Clone)]
    pub struct InitializeExtraAccountMetaListInstructionAccounts {
        pub payer: Pubkey,

        pub extra_account_meta_list: Pubkey,

        pub mint: Pubkey,

        pub sss_token_program: Pubkey,

        pub roles_config: Pubkey,
    }

    impl InitializeExtraAccountMetaListInstructionAccounts {
        pub fn new(
            payer: Pubkey,

            extra_account_meta_list: Pubkey,

            mint: Pubkey,

            sss_token_program: Pubkey,

            roles_config: Pubkey,
        ) -> Self {
            Self {
                payer,

                extra_account_meta_list,

                mint,

                sss_token_program,

                roles_config,
            }
        }
    }

    /// Instruction data for InitializeExtraAccountMetaList
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct InitializeExtraAccountMetaListInstructionData {}

    impl InitializeExtraAccountMetaListInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for InitializeExtraAccountMetaListInstruction
    impl InitializeExtraAccountMetaListInstruction {
        fn discriminator() -> [u8; 8] {
            [92u8, 197u8, 174u8, 197u8, 41u8, 124u8, 19u8, 3u8]
        }

        pub fn data(data: InitializeExtraAccountMetaListInstructionData) -> Self {
            Self {
                accounts: InitializeExtraAccountMetaListInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(
            mut self,
            accounts: InitializeExtraAccountMetaListInstructionAccounts,
        ) -> Self {
            self.accounts.payer = AccountMeta::new(accounts.payer, true);

            self.accounts.extra_account_meta_list =
                AccountMeta::new(accounts.extra_account_meta_list, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.sss_token_program =
                AccountMeta::new_readonly(accounts.sss_token_program, false);

            self.accounts.roles_config = AccountMeta::new_readonly(accounts.roles_config, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.payer.clone());

            metas.push(self.accounts.extra_account_meta_list.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.sss_token_program.clone());

            metas.push(self.accounts.roles_config.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: TransferHook
    // ....................................................................

    /// Main instruction struct for TransferHook
    pub struct TransferHookInstruction {
        pub accounts: TransferHookInstructionAccountMetas,
        pub data: TransferHookInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for TransferHook instruction
    #[derive(Debug, Clone, Default)]
    pub struct TransferHookInstructionAccountMetas {
        pub source_token: AccountMeta,

        pub mint: AccountMeta,

        pub destination_token: AccountMeta,

        pub authority: AccountMeta,

        pub extra_account_meta_list: AccountMeta,

        pub sss_token_program: AccountMeta,

        pub source_blacklist_entry: AccountMeta,

        pub destination_blacklist_entry: AccountMeta,

        pub stablecoin_state: AccountMeta,
    }

    /// Account pubkeys for TransferHook instruction
    #[derive(Debug, Clone)]
    pub struct TransferHookInstructionAccounts {
        pub source_token: Pubkey,

        pub mint: Pubkey,

        pub destination_token: Pubkey,

        pub authority: Pubkey,

        pub extra_account_meta_list: Pubkey,

        pub sss_token_program: Pubkey,

        pub source_blacklist_entry: Pubkey,

        pub destination_blacklist_entry: Pubkey,

        pub stablecoin_state: Pubkey,
    }

    impl TransferHookInstructionAccounts {
        pub fn new(
            source_token: Pubkey,

            mint: Pubkey,

            destination_token: Pubkey,

            authority: Pubkey,

            extra_account_meta_list: Pubkey,

            sss_token_program: Pubkey,

            source_blacklist_entry: Pubkey,

            destination_blacklist_entry: Pubkey,

            stablecoin_state: Pubkey,
        ) -> Self {
            Self {
                source_token,

                mint,

                destination_token,

                authority,

                extra_account_meta_list,

                sss_token_program,

                source_blacklist_entry,

                destination_blacklist_entry,

                stablecoin_state,
            }
        }
    }

    /// Instruction data for TransferHook
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct TransferHookInstructionData {
        pub amount: u64,
    }

    impl TransferHookInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for TransferHookInstruction
    impl TransferHookInstruction {
        fn discriminator() -> [u8; 8] {
            [220u8, 57u8, 220u8, 152u8, 126u8, 125u8, 97u8, 168u8]
        }

        pub fn data(data: TransferHookInstructionData) -> Self {
            Self {
                accounts: TransferHookInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: TransferHookInstructionAccounts) -> Self {
            self.accounts.source_token = AccountMeta::new_readonly(accounts.source_token, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.destination_token =
                AccountMeta::new_readonly(accounts.destination_token, false);

            self.accounts.authority = AccountMeta::new_readonly(accounts.authority, false);

            self.accounts.extra_account_meta_list =
                AccountMeta::new_readonly(accounts.extra_account_meta_list, false);

            self.accounts.sss_token_program =
                AccountMeta::new_readonly(accounts.sss_token_program, false);

            self.accounts.source_blacklist_entry =
                AccountMeta::new_readonly(accounts.source_blacklist_entry, false);

            self.accounts.destination_blacklist_entry =
                AccountMeta::new_readonly(accounts.destination_blacklist_entry, false);

            self.accounts.stablecoin_state =
                AccountMeta::new_readonly(accounts.stablecoin_state, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.source_token.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.destination_token.clone());

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.extra_account_meta_list.clone());

            metas.push(self.accounts.sss_token_program.clone());

            metas.push(self.accounts.source_blacklist_entry.clone());

            metas.push(self.accounts.destination_blacklist_entry.clone());

            metas.push(self.accounts.stablecoin_state.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

// ============================================================================
// END OF GENERATED FILE
// ============================================================================
