[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
sss_token = "EsfnG79GeuaxGxnttbJ2kHYRs8CwP5RNNMbr6a3MiZaK"
transfer_hook = "F8wwXWp8JUKVrDPwFCpG2NrheV3X7KKatoDuiYeBigkf"
sss_oracle = "7gw6jAKSZx4mueRHcT8kxtjWen9X53NJdKHrXNUwUQrd"

[programs.devnet]
sss_token = "EsfnG79GeuaxGxnttbJ2kHYRs8CwP5RNNMbr6a3MiZaK"
transfer_hook = "F8wwXWp8JUKVrDPwFCpG2NrheV3X7KKatoDuiYeBigkf"
sss_oracle = "7gw6jAKSZx4mueRHcT8kxtjWen9X53NJdKHrXNUwUQrd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/anchor/**/*.ts"

[workspace]
members = [
    "programs/sss-token",
    "programs/transfer-hook",
    "programs/sss-oracle",
]
