//! # Trident Generated Types
//!
//! This file is automatically generated by Trident.
//! **DO NOT EDIT THIS FILE MANUALLY**

#![allow(dead_code)]
#![allow(unused_imports)]

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use trident_fuzz::fuzzing::*;

// ============================================================================
// PROGRAM MODULES
// ============================================================================

// ----------------------------------------------------------------------------
// Program: sss_oracle
// ----------------------------------------------------------------------------
pub mod sss_oracle {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for sss_oracle
    pub fn program_id() -> Pubkey {
        pubkey!("7gw6jAKSZx4mueRHcT8kxtjWen9X53NJdKHrXNUwUQrd")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: AddFeed
    // ....................................................................

    /// Main instruction struct for AddFeed
    pub struct AddFeedInstruction {
        pub accounts: AddFeedInstructionAccountMetas,
        pub data: AddFeedInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for AddFeed instruction
    #[derive(Debug, Clone, Default)]
    pub struct AddFeedInstructionAccountMetas {
        pub authority: AccountMeta,

        pub oracle_config: AccountMeta,

        pub price_feed_entry: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for AddFeed instruction
    #[derive(Debug, Clone)]
    pub struct AddFeedInstructionAccounts {
        pub authority: Pubkey,

        pub oracle_config: Pubkey,

        pub price_feed_entry: Pubkey,
    }

    impl AddFeedInstructionAccounts {
        pub fn new(authority: Pubkey, oracle_config: Pubkey, price_feed_entry: Pubkey) -> Self {
            Self {
                authority,

                oracle_config,

                price_feed_entry,
            }
        }
    }

    /// Instruction data for AddFeed
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct AddFeedInstructionData {
        pub params: AddFeedParams,
    }

    impl AddFeedInstructionData {
        pub fn new(params: AddFeedParams) -> Self {
            Self { params }
        }
    }

    /// Implementation for AddFeedInstruction
    impl AddFeedInstruction {
        fn discriminator() -> [u8; 8] {
            [10u8, 51u8, 6u8, 82u8, 130u8, 110u8, 98u8, 232u8]
        }

        pub fn data(data: AddFeedInstructionData) -> Self {
            Self {
                accounts: AddFeedInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: AddFeedInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.oracle_config = AccountMeta::new(accounts.oracle_config, false);

            self.accounts.price_feed_entry = AccountMeta::new(accounts.price_feed_entry, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.oracle_config.clone());

            metas.push(self.accounts.price_feed_entry.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Aggregate
    // ....................................................................

    /// Main instruction struct for Aggregate
    pub struct AggregateInstruction {
        pub accounts: AggregateInstructionAccountMetas,
        pub data: AggregateInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Aggregate instruction
    #[derive(Debug, Clone, Default)]
    pub struct AggregateInstructionAccountMetas {
        pub cranker: AccountMeta,

        pub oracle_config: AccountMeta,
    }

    /// Account pubkeys for Aggregate instruction
    #[derive(Debug, Clone)]
    pub struct AggregateInstructionAccounts {
        pub cranker: Pubkey,

        pub oracle_config: Pubkey,
    }

    impl AggregateInstructionAccounts {
        pub fn new(cranker: Pubkey, oracle_config: Pubkey) -> Self {
            Self {
                cranker,

                oracle_config,
            }
        }
    }

    /// Instruction data for Aggregate
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct AggregateInstructionData {}

    impl AggregateInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for AggregateInstruction
    impl AggregateInstruction {
        fn discriminator() -> [u8; 8] {
            [211u8, 113u8, 179u8, 217u8, 7u8, 100u8, 44u8, 8u8]
        }

        pub fn data(data: AggregateInstructionData) -> Self {
            Self {
                accounts: AggregateInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: AggregateInstructionAccounts) -> Self {
            self.accounts.cranker = AccountMeta::new_readonly(accounts.cranker, true);

            self.accounts.oracle_config = AccountMeta::new(accounts.oracle_config, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.cranker.clone());

            metas.push(self.accounts.oracle_config.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: CloseOracle
    // ....................................................................

    /// Main instruction struct for CloseOracle
    pub struct CloseOracleInstruction {
        pub accounts: CloseOracleInstructionAccountMetas,
        pub data: CloseOracleInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CloseOracle instruction
    #[derive(Debug, Clone, Default)]
    pub struct CloseOracleInstructionAccountMetas {
        pub authority: AccountMeta,

        pub oracle_config: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for CloseOracle instruction
    #[derive(Debug, Clone)]
    pub struct CloseOracleInstructionAccounts {
        pub authority: Pubkey,

        pub oracle_config: Pubkey,
    }

    impl CloseOracleInstructionAccounts {
        pub fn new(authority: Pubkey, oracle_config: Pubkey) -> Self {
            Self {
                authority,

                oracle_config,
            }
        }
    }

    /// Instruction data for CloseOracle
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CloseOracleInstructionData {}

    impl CloseOracleInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for CloseOracleInstruction
    impl CloseOracleInstruction {
        fn discriminator() -> [u8; 8] {
            [74u8, 239u8, 49u8, 223u8, 206u8, 52u8, 189u8, 123u8]
        }

        pub fn data(data: CloseOracleInstructionData) -> Self {
            Self {
                accounts: CloseOracleInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CloseOracleInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.oracle_config = AccountMeta::new(accounts.oracle_config, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.oracle_config.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: CrankFeed
    // ....................................................................

    /// Main instruction struct for CrankFeed
    pub struct CrankFeedInstruction {
        pub accounts: CrankFeedInstructionAccountMetas,
        pub data: CrankFeedInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CrankFeed instruction
    #[derive(Debug, Clone, Default)]
    pub struct CrankFeedInstructionAccountMetas {
        pub cranker: AccountMeta,

        pub oracle_config: AccountMeta,

        pub price_feed_entry: AccountMeta,
    }

    /// Account pubkeys for CrankFeed instruction
    #[derive(Debug, Clone)]
    pub struct CrankFeedInstructionAccounts {
        pub cranker: Pubkey,

        pub oracle_config: Pubkey,

        pub price_feed_entry: Pubkey,
    }

    impl CrankFeedInstructionAccounts {
        pub fn new(cranker: Pubkey, oracle_config: Pubkey, price_feed_entry: Pubkey) -> Self {
            Self {
                cranker,

                oracle_config,

                price_feed_entry,
            }
        }
    }

    /// Instruction data for CrankFeed
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CrankFeedInstructionData {
        pub price: u64,

        pub confidence: u64,
    }

    impl CrankFeedInstructionData {
        pub fn new(price: u64, confidence: u64) -> Self {
            Self { price, confidence }
        }
    }

    /// Implementation for CrankFeedInstruction
    impl CrankFeedInstruction {
        fn discriminator() -> [u8; 8] {
            [134u8, 74u8, 251u8, 229u8, 196u8, 148u8, 177u8, 59u8]
        }

        pub fn data(data: CrankFeedInstructionData) -> Self {
            Self {
                accounts: CrankFeedInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CrankFeedInstructionAccounts) -> Self {
            self.accounts.cranker = AccountMeta::new_readonly(accounts.cranker, true);

            self.accounts.oracle_config = AccountMeta::new_readonly(accounts.oracle_config, false);

            self.accounts.price_feed_entry = AccountMeta::new(accounts.price_feed_entry, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.cranker.clone());

            metas.push(self.accounts.oracle_config.clone());

            metas.push(self.accounts.price_feed_entry.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: GetMintPrice
    // ....................................................................

    /// Main instruction struct for GetMintPrice
    pub struct GetMintPriceInstruction {
        pub accounts: GetMintPriceInstructionAccountMetas,
        pub data: GetMintPriceInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for GetMintPrice instruction
    #[derive(Debug, Clone, Default)]
    pub struct GetMintPriceInstructionAccountMetas {
        pub oracle_config: AccountMeta,
    }

    /// Account pubkeys for GetMintPrice instruction
    #[derive(Debug, Clone)]
    pub struct GetMintPriceInstructionAccounts {
        pub oracle_config: Pubkey,
    }

    impl GetMintPriceInstructionAccounts {
        pub fn new(oracle_config: Pubkey) -> Self {
            Self { oracle_config }
        }
    }

    /// Instruction data for GetMintPrice
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct GetMintPriceInstructionData {}

    impl GetMintPriceInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for GetMintPriceInstruction
    impl GetMintPriceInstruction {
        fn discriminator() -> [u8; 8] {
            [223u8, 126u8, 22u8, 191u8, 69u8, 57u8, 84u8, 219u8]
        }

        pub fn data(data: GetMintPriceInstructionData) -> Self {
            Self {
                accounts: GetMintPriceInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: GetMintPriceInstructionAccounts) -> Self {
            self.accounts.oracle_config = AccountMeta::new_readonly(accounts.oracle_config, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.oracle_config.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: GetRedeemPrice
    // ....................................................................

    /// Main instruction struct for GetRedeemPrice
    pub struct GetRedeemPriceInstruction {
        pub accounts: GetRedeemPriceInstructionAccountMetas,
        pub data: GetRedeemPriceInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for GetRedeemPrice instruction
    #[derive(Debug, Clone, Default)]
    pub struct GetRedeemPriceInstructionAccountMetas {
        pub oracle_config: AccountMeta,
    }

    /// Account pubkeys for GetRedeemPrice instruction
    #[derive(Debug, Clone)]
    pub struct GetRedeemPriceInstructionAccounts {
        pub oracle_config: Pubkey,
    }

    impl GetRedeemPriceInstructionAccounts {
        pub fn new(oracle_config: Pubkey) -> Self {
            Self { oracle_config }
        }
    }

    /// Instruction data for GetRedeemPrice
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct GetRedeemPriceInstructionData {}

    impl GetRedeemPriceInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for GetRedeemPriceInstruction
    impl GetRedeemPriceInstruction {
        fn discriminator() -> [u8; 8] {
            [246u8, 58u8, 171u8, 53u8, 32u8, 70u8, 153u8, 3u8]
        }

        pub fn data(data: GetRedeemPriceInstructionData) -> Self {
            Self {
                accounts: GetRedeemPriceInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: GetRedeemPriceInstructionAccounts) -> Self {
            self.accounts.oracle_config = AccountMeta::new_readonly(accounts.oracle_config, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.oracle_config.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: InitializeOracle
    // ....................................................................

    /// Main instruction struct for InitializeOracle
    pub struct InitializeOracleInstruction {
        pub accounts: InitializeOracleInstructionAccountMetas,
        pub data: InitializeOracleInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for InitializeOracle instruction
    #[derive(Debug, Clone, Default)]
    pub struct InitializeOracleInstructionAccountMetas {
        pub authority: AccountMeta,

        pub mint: AccountMeta,

        pub oracle_config: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for InitializeOracle instruction
    #[derive(Debug, Clone)]
    pub struct InitializeOracleInstructionAccounts {
        pub authority: Pubkey,

        pub mint: Pubkey,

        pub oracle_config: Pubkey,
    }

    impl InitializeOracleInstructionAccounts {
        pub fn new(authority: Pubkey, mint: Pubkey, oracle_config: Pubkey) -> Self {
            Self {
                authority,

                mint,

                oracle_config,
            }
        }
    }

    /// Instruction data for InitializeOracle
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct InitializeOracleInstructionData {
        pub params: InitializeOracleParams,
    }

    impl InitializeOracleInstructionData {
        pub fn new(params: InitializeOracleParams) -> Self {
            Self { params }
        }
    }

    /// Implementation for InitializeOracleInstruction
    impl InitializeOracleInstruction {
        fn discriminator() -> [u8; 8] {
            [144u8, 223u8, 131u8, 120u8, 196u8, 253u8, 181u8, 99u8]
        }

        pub fn data(data: InitializeOracleInstructionData) -> Self {
            Self {
                accounts: InitializeOracleInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: InitializeOracleInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.oracle_config = AccountMeta::new(accounts.oracle_config, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.oracle_config.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: RemoveFeed
    // ....................................................................

    /// Main instruction struct for RemoveFeed
    pub struct RemoveFeedInstruction {
        pub accounts: RemoveFeedInstructionAccountMetas,
        pub data: RemoveFeedInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for RemoveFeed instruction
    #[derive(Debug, Clone, Default)]
    pub struct RemoveFeedInstructionAccountMetas {
        pub authority: AccountMeta,

        pub oracle_config: AccountMeta,

        pub price_feed_entry: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for RemoveFeed instruction
    #[derive(Debug, Clone)]
    pub struct RemoveFeedInstructionAccounts {
        pub authority: Pubkey,

        pub oracle_config: Pubkey,

        pub price_feed_entry: Pubkey,
    }

    impl RemoveFeedInstructionAccounts {
        pub fn new(authority: Pubkey, oracle_config: Pubkey, price_feed_entry: Pubkey) -> Self {
            Self {
                authority,

                oracle_config,

                price_feed_entry,
            }
        }
    }

    /// Instruction data for RemoveFeed
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct RemoveFeedInstructionData {
        pub feed_index: u8,
    }

    impl RemoveFeedInstructionData {
        pub fn new(feed_index: u8) -> Self {
            Self { feed_index }
        }
    }

    /// Implementation for RemoveFeedInstruction
    impl RemoveFeedInstruction {
        fn discriminator() -> [u8; 8] {
            [38u8, 151u8, 108u8, 178u8, 94u8, 82u8, 223u8, 57u8]
        }

        pub fn data(data: RemoveFeedInstructionData) -> Self {
            Self {
                accounts: RemoveFeedInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: RemoveFeedInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.oracle_config = AccountMeta::new(accounts.oracle_config, false);

            self.accounts.price_feed_entry = AccountMeta::new(accounts.price_feed_entry, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.oracle_config.clone());

            metas.push(self.accounts.price_feed_entry.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: SetManualPrice
    // ....................................................................

    /// Main instruction struct for SetManualPrice
    pub struct SetManualPriceInstruction {
        pub accounts: SetManualPriceInstructionAccountMetas,
        pub data: SetManualPriceInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for SetManualPrice instruction
    #[derive(Debug, Clone, Default)]
    pub struct SetManualPriceInstructionAccountMetas {
        pub authority: AccountMeta,

        pub oracle_config: AccountMeta,
    }

    /// Account pubkeys for SetManualPrice instruction
    #[derive(Debug, Clone)]
    pub struct SetManualPriceInstructionAccounts {
        pub authority: Pubkey,

        pub oracle_config: Pubkey,
    }

    impl SetManualPriceInstructionAccounts {
        pub fn new(authority: Pubkey, oracle_config: Pubkey) -> Self {
            Self {
                authority,

                oracle_config,
            }
        }
    }

    /// Instruction data for SetManualPrice
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct SetManualPriceInstructionData {
        pub price: u64,

        pub active: bool,
    }

    impl SetManualPriceInstructionData {
        pub fn new(price: u64, active: bool) -> Self {
            Self { price, active }
        }
    }

    /// Implementation for SetManualPriceInstruction
    impl SetManualPriceInstruction {
        fn discriminator() -> [u8; 8] {
            [6u8, 210u8, 4u8, 51u8, 43u8, 53u8, 139u8, 140u8]
        }

        pub fn data(data: SetManualPriceInstructionData) -> Self {
            Self {
                accounts: SetManualPriceInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: SetManualPriceInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new_readonly(accounts.authority, true);

            self.accounts.oracle_config = AccountMeta::new(accounts.oracle_config, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.oracle_config.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: TransferOracleAuthority
    // ....................................................................

    /// Main instruction struct for TransferOracleAuthority
    pub struct TransferOracleAuthorityInstruction {
        pub accounts: TransferOracleAuthorityInstructionAccountMetas,
        pub data: TransferOracleAuthorityInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for TransferOracleAuthority instruction
    #[derive(Debug, Clone, Default)]
    pub struct TransferOracleAuthorityInstructionAccountMetas {
        pub caller: AccountMeta,

        pub oracle_config: AccountMeta,
    }

    /// Account pubkeys for TransferOracleAuthority instruction
    #[derive(Debug, Clone)]
    pub struct TransferOracleAuthorityInstructionAccounts {
        pub caller: Pubkey,

        pub oracle_config: Pubkey,
    }

    impl TransferOracleAuthorityInstructionAccounts {
        pub fn new(caller: Pubkey, oracle_config: Pubkey) -> Self {
            Self {
                caller,

                oracle_config,
            }
        }
    }

    /// Instruction data for TransferOracleAuthority
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct TransferOracleAuthorityInstructionData {
        pub new_authority: Option<Pubkey>,
    }

    impl TransferOracleAuthorityInstructionData {
        pub fn new(new_authority: Option<Pubkey>) -> Self {
            Self { new_authority }
        }
    }

    /// Implementation for TransferOracleAuthorityInstruction
    impl TransferOracleAuthorityInstruction {
        fn discriminator() -> [u8; 8] {
            [121u8, 248u8, 188u8, 188u8, 98u8, 217u8, 168u8, 20u8]
        }

        pub fn data(data: TransferOracleAuthorityInstructionData) -> Self {
            Self {
                accounts: TransferOracleAuthorityInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: TransferOracleAuthorityInstructionAccounts) -> Self {
            self.accounts.caller = AccountMeta::new_readonly(accounts.caller, true);

            self.accounts.oracle_config = AccountMeta::new(accounts.oracle_config, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.caller.clone());

            metas.push(self.accounts.oracle_config.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: UpdateOracleConfig
    // ....................................................................

    /// Main instruction struct for UpdateOracleConfig
    pub struct UpdateOracleConfigInstruction {
        pub accounts: UpdateOracleConfigInstructionAccountMetas,
        pub data: UpdateOracleConfigInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for UpdateOracleConfig instruction
    #[derive(Debug, Clone, Default)]
    pub struct UpdateOracleConfigInstructionAccountMetas {
        pub authority: AccountMeta,

        pub oracle_config: AccountMeta,
    }

    /// Account pubkeys for UpdateOracleConfig instruction
    #[derive(Debug, Clone)]
    pub struct UpdateOracleConfigInstructionAccounts {
        pub authority: Pubkey,

        pub oracle_config: Pubkey,
    }

    impl UpdateOracleConfigInstructionAccounts {
        pub fn new(authority: Pubkey, oracle_config: Pubkey) -> Self {
            Self {
                authority,

                oracle_config,
            }
        }
    }

    /// Instruction data for UpdateOracleConfig
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct UpdateOracleConfigInstructionData {
        pub params: UpdateOracleConfigParams,
    }

    impl UpdateOracleConfigInstructionData {
        pub fn new(params: UpdateOracleConfigParams) -> Self {
            Self { params }
        }
    }

    /// Implementation for UpdateOracleConfigInstruction
    impl UpdateOracleConfigInstruction {
        fn discriminator() -> [u8; 8] {
            [83u8, 16u8, 11u8, 254u8, 57u8, 99u8, 156u8, 58u8]
        }

        pub fn data(data: UpdateOracleConfigInstructionData) -> Self {
            Self {
                accounts: UpdateOracleConfigInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: UpdateOracleConfigInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new_readonly(accounts.authority, true);

            self.accounts.oracle_config = AccountMeta::new(accounts.oracle_config, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.oracle_config.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

/// Custom struct: AddFeedParams
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct AddFeedParams {
    pub feed_index: u8,

    pub feed_type: u8,

    pub feed_address: Pubkey,

    pub label: String,

    pub weight: u16,

    pub max_staleness_override: i64,
}

impl AddFeedParams {
    pub fn new(
        feed_index: u8,

        feed_type: u8,

        feed_address: Pubkey,

        label: String,

        weight: u16,

        max_staleness_override: i64,
    ) -> Self {
        Self {
            feed_index,

            feed_type,

            feed_address,

            label,

            weight,

            max_staleness_override,
        }
    }
}

/// Custom struct: FeedAdded
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct FeedAdded {
    pub oracle_config: Pubkey,

    pub feed_entry: Pubkey,

    pub feed_index: u8,

    pub feed_type: u8,

    pub label: String,
}

impl FeedAdded {
    pub fn new(
        oracle_config: Pubkey,

        feed_entry: Pubkey,

        feed_index: u8,

        feed_type: u8,

        label: String,
    ) -> Self {
        Self {
            oracle_config,

            feed_entry,

            feed_index,

            feed_type,

            label,
        }
    }
}

/// Custom struct: FeedCranked
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct FeedCranked {
    pub oracle_config: Pubkey,

    pub feed_index: u8,

    pub price: u64,

    pub confidence: u64,

    pub timestamp: i64,
}

impl FeedCranked {
    pub fn new(
        oracle_config: Pubkey,

        feed_index: u8,

        price: u64,

        confidence: u64,

        timestamp: i64,
    ) -> Self {
        Self {
            oracle_config,

            feed_index,

            price,

            confidence,

            timestamp,
        }
    }
}

/// Custom struct: FeedRemoved
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct FeedRemoved {
    pub oracle_config: Pubkey,

    pub feed_index: u8,
}

impl FeedRemoved {
    pub fn new(oracle_config: Pubkey, feed_index: u8) -> Self {
        Self {
            oracle_config,

            feed_index,
        }
    }
}

/// Custom struct: InitializeOracleParams
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct InitializeOracleParams {
    pub base_currency: String,

    pub quote_currency: String,

    pub max_staleness_seconds: i64,

    pub max_confidence_interval_bps: u16,

    pub aggregation_method: u8,

    pub min_feeds_required: u8,

    pub deviation_threshold_bps: u16,

    pub max_price_change_bps: u16,

    pub mint_premium_bps: i16,

    pub redeem_discount_bps: i16,

    pub cranker: Pubkey,
}

impl InitializeOracleParams {
    pub fn new(
        base_currency: String,

        quote_currency: String,

        max_staleness_seconds: i64,

        max_confidence_interval_bps: u16,

        aggregation_method: u8,

        min_feeds_required: u8,

        deviation_threshold_bps: u16,

        max_price_change_bps: u16,

        mint_premium_bps: i16,

        redeem_discount_bps: i16,

        cranker: Pubkey,
    ) -> Self {
        Self {
            base_currency,

            quote_currency,

            max_staleness_seconds,

            max_confidence_interval_bps,

            aggregation_method,

            min_feeds_required,

            deviation_threshold_bps,

            max_price_change_bps,

            mint_premium_bps,

            redeem_discount_bps,

            cranker,
        }
    }
}

/// Custom struct: ManualPriceSet
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct ManualPriceSet {
    pub oracle_config: Pubkey,

    pub price: u64,

    pub active: bool,
}

impl ManualPriceSet {
    pub fn new(oracle_config: Pubkey, price: u64, active: bool) -> Self {
        Self {
            oracle_config,

            price,

            active,
        }
    }
}

/// Custom struct: MintPriceComputed
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct MintPriceComputed {
    pub oracle_config: Pubkey,

    pub base_price: u64,

    pub mint_price: u64,

    pub premium_bps: i16,
}

impl MintPriceComputed {
    pub fn new(oracle_config: Pubkey, base_price: u64, mint_price: u64, premium_bps: i16) -> Self {
        Self {
            oracle_config,

            base_price,

            mint_price,

            premium_bps,
        }
    }
}

/// Custom struct: OracleAuthorityTransferCancelled
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct OracleAuthorityTransferCancelled {
    pub oracle_config: Pubkey,

    pub cancelled_by: Pubkey,

    pub was_pending: Pubkey,

    pub timestamp: i64,
}

impl OracleAuthorityTransferCancelled {
    pub fn new(
        oracle_config: Pubkey,

        cancelled_by: Pubkey,

        was_pending: Pubkey,

        timestamp: i64,
    ) -> Self {
        Self {
            oracle_config,

            cancelled_by,

            was_pending,

            timestamp,
        }
    }
}

/// Custom struct: OracleAuthorityTransferCompleted
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct OracleAuthorityTransferCompleted {
    pub oracle_config: Pubkey,

    pub new_authority: Pubkey,

    pub timestamp: i64,
}

impl OracleAuthorityTransferCompleted {
    pub fn new(oracle_config: Pubkey, new_authority: Pubkey, timestamp: i64) -> Self {
        Self {
            oracle_config,

            new_authority,

            timestamp,
        }
    }
}

/// Custom struct: OracleAuthorityTransferInitiated
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct OracleAuthorityTransferInitiated {
    pub oracle_config: Pubkey,

    pub current_authority: Pubkey,

    pub pending_authority: Pubkey,

    pub timestamp: i64,
}

impl OracleAuthorityTransferInitiated {
    pub fn new(
        oracle_config: Pubkey,

        current_authority: Pubkey,

        pending_authority: Pubkey,

        timestamp: i64,
    ) -> Self {
        Self {
            oracle_config,

            current_authority,

            pending_authority,

            timestamp,
        }
    }
}

/// Custom struct: OracleClosed
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct OracleClosed {
    pub oracle_config: Pubkey,

    pub authority: Pubkey,
}

impl OracleClosed {
    pub fn new(oracle_config: Pubkey, authority: Pubkey) -> Self {
        Self {
            oracle_config,

            authority,
        }
    }
}

/// Custom struct: OracleConfig
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct OracleConfig {
    pub version: u8,

    pub authority: Pubkey,

    pub pending_authority: Option<Pubkey>,

    pub cranker: Pubkey,

    pub mint: Pubkey,

    pub base_currency: String,

    pub quote_currency: String,

    pub max_staleness_seconds: i64,

    pub max_confidence_interval_bps: u16,

    pub aggregation_method: u8,

    pub min_feeds_required: u8,

    pub deviation_threshold_bps: u16,

    pub max_price_change_bps: u16,

    pub mint_premium_bps: i16,

    pub redeem_discount_bps: i16,

    pub manual_price: u64,

    pub manual_price_active: bool,

    pub last_aggregated_price: u64,

    pub last_aggregated_confidence: u64,

    pub last_aggregated_timestamp: i64,

    pub feed_count: u8,

    pub paused: bool,

    pub bump: u8,

    pub reserved: [u8; 32],
}

impl OracleConfig {
    pub fn new(
        version: u8,

        authority: Pubkey,

        pending_authority: Option<Pubkey>,

        cranker: Pubkey,

        mint: Pubkey,

        base_currency: String,

        quote_currency: String,

        max_staleness_seconds: i64,

        max_confidence_interval_bps: u16,

        aggregation_method: u8,

        min_feeds_required: u8,

        deviation_threshold_bps: u16,

        max_price_change_bps: u16,

        mint_premium_bps: i16,

        redeem_discount_bps: i16,

        manual_price: u64,

        manual_price_active: bool,

        last_aggregated_price: u64,

        last_aggregated_confidence: u64,

        last_aggregated_timestamp: i64,

        feed_count: u8,

        paused: bool,

        bump: u8,

        reserved: [u8; 32],
    ) -> Self {
        Self {
            version,

            authority,

            pending_authority,

            cranker,

            mint,

            base_currency,

            quote_currency,

            max_staleness_seconds,

            max_confidence_interval_bps,

            aggregation_method,

            min_feeds_required,

            deviation_threshold_bps,

            max_price_change_bps,

            mint_premium_bps,

            redeem_discount_bps,

            manual_price,

            manual_price_active,

            last_aggregated_price,

            last_aggregated_confidence,

            last_aggregated_timestamp,

            feed_count,

            paused,

            bump,

            reserved,
        }
    }
}

/// Custom struct: OracleConfigUpdated
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct OracleConfigUpdated {
    pub oracle_config: Pubkey,

    pub authority: Pubkey,
}

impl OracleConfigUpdated {
    pub fn new(oracle_config: Pubkey, authority: Pubkey) -> Self {
        Self {
            oracle_config,

            authority,
        }
    }
}

/// Custom struct: OracleInitialized
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct OracleInitialized {
    pub oracle_config: Pubkey,

    pub authority: Pubkey,

    pub mint: Pubkey,

    pub base_currency: String,

    pub quote_currency: String,
}

impl OracleInitialized {
    pub fn new(
        oracle_config: Pubkey,

        authority: Pubkey,

        mint: Pubkey,

        base_currency: String,

        quote_currency: String,
    ) -> Self {
        Self {
            oracle_config,

            authority,

            mint,

            base_currency,

            quote_currency,
        }
    }
}

/// Custom struct: OraclePauseStateChanged
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct OraclePauseStateChanged {
    pub oracle_config: Pubkey,

    pub paused: bool,

    pub authority: Pubkey,

    pub timestamp: i64,
}

impl OraclePauseStateChanged {
    pub fn new(oracle_config: Pubkey, paused: bool, authority: Pubkey, timestamp: i64) -> Self {
        Self {
            oracle_config,

            paused,

            authority,

            timestamp,
        }
    }
}

/// Custom struct: PriceAggregated
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct PriceAggregated {
    pub oracle_config: Pubkey,

    pub aggregated_price: u64,

    pub aggregated_confidence: u64,

    pub feeds_used: u8,

    pub timestamp: i64,
}

impl PriceAggregated {
    pub fn new(
        oracle_config: Pubkey,

        aggregated_price: u64,

        aggregated_confidence: u64,

        feeds_used: u8,

        timestamp: i64,
    ) -> Self {
        Self {
            oracle_config,

            aggregated_price,

            aggregated_confidence,

            feeds_used,

            timestamp,
        }
    }
}

/// Custom struct: PriceFeedEntry
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct PriceFeedEntry {
    pub oracle_config: Pubkey,

    pub feed_index: u8,

    pub feed_type: u8,

    pub feed_address: Pubkey,

    pub label: String,

    pub last_price: u64,

    pub last_confidence: u64,

    pub last_timestamp: i64,

    pub weight: u16,

    pub enabled: bool,

    pub max_staleness_override: i64,

    pub bump: u8,

    pub reserved: [u8; 32],
}

impl PriceFeedEntry {
    pub fn new(
        oracle_config: Pubkey,

        feed_index: u8,

        feed_type: u8,

        feed_address: Pubkey,

        label: String,

        last_price: u64,

        last_confidence: u64,

        last_timestamp: i64,

        weight: u16,

        enabled: bool,

        max_staleness_override: i64,

        bump: u8,

        reserved: [u8; 32],
    ) -> Self {
        Self {
            oracle_config,

            feed_index,

            feed_type,

            feed_address,

            label,

            last_price,

            last_confidence,

            last_timestamp,

            weight,

            enabled,

            max_staleness_override,

            bump,

            reserved,
        }
    }
}

/// Custom struct: RedeemPriceComputed
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct RedeemPriceComputed {
    pub oracle_config: Pubkey,

    pub base_price: u64,

    pub redeem_price: u64,

    pub discount_bps: i16,
}

impl RedeemPriceComputed {
    pub fn new(
        oracle_config: Pubkey,

        base_price: u64,

        redeem_price: u64,

        discount_bps: i16,
    ) -> Self {
        Self {
            oracle_config,

            base_price,

            redeem_price,

            discount_bps,
        }
    }
}

/// Custom struct: UpdateOracleConfigParams
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct UpdateOracleConfigParams {
    pub max_staleness_seconds: Option<i64>,

    pub max_confidence_interval_bps: Option<u16>,

    pub aggregation_method: Option<u8>,

    pub min_feeds_required: Option<u8>,

    pub deviation_threshold_bps: Option<u16>,

    pub max_price_change_bps: Option<u16>,

    pub mint_premium_bps: Option<i16>,

    pub redeem_discount_bps: Option<i16>,

    pub cranker: Option<Pubkey>,

    pub paused: Option<bool>,
}

impl UpdateOracleConfigParams {
    pub fn new(
        max_staleness_seconds: Option<i64>,

        max_confidence_interval_bps: Option<u16>,

        aggregation_method: Option<u8>,

        min_feeds_required: Option<u8>,

        deviation_threshold_bps: Option<u16>,

        max_price_change_bps: Option<u16>,

        mint_premium_bps: Option<i16>,

        redeem_discount_bps: Option<i16>,

        cranker: Option<Pubkey>,

        paused: Option<bool>,
    ) -> Self {
        Self {
            max_staleness_seconds,

            max_confidence_interval_bps,

            aggregation_method,

            min_feeds_required,

            deviation_threshold_bps,

            max_price_change_bps,

            mint_premium_bps,

            redeem_discount_bps,

            cranker,

            paused,
        }
    }
}

// ============================================================================
// END OF GENERATED FILE
// ============================================================================
