import * as anchor from '@coral-xyz/anchor';
import { Program } from '@coral-xyz/anchor';
import { Connection, Keypair, PublicKey } from '@solana/web3.js';
import { expect } from 'chai';
import { SsolanaStablecoin, Presets } from '@stbr/sss-token-sdk';
// IDL types auto-generated by `anchor build`
// import { SssToken } from '../../target/types/sss_token';

describe('SSS-1: Minimal Stablecoin', () => {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);
  const connection = provider.connection;
  const authority = (provider.wallet as anchor.Wallet).payer;

  let stable: any; // SolanaStablecoin

  before('Initialize SSS-1 stablecoin', async () => {
    stable = await (await import('@stbr/sss-token-sdk')).SolanaStablecoin.create(connection, {
      preset: Presets.SSS_1,
      name: 'Test Dollar',
      symbol: 'TUSD',
      decimals: 6,
      uri: 'https://example.com/tusd.json',
      authority,
    });
    expect(stable.mint).to.be.instanceOf(PublicKey);
    console.log('  Mint:', stable.mint.toBase58());
  });

  it('SSS-1: getStatus returns correct fields', async () => {
    const status = await stable.getStatus();
    expect(status.name).to.equal('Test Dollar');
    expect(status.symbol).to.equal('TUSD');
    expect(status.decimals).to.equal(6);
    expect(status.paused).to.be.false;
    expect(status.enablePermanentDelegate).to.be.false;
    expect(status.enableTransferHook).to.be.false;
  });

  it('SSS-1: updateMinter registers minter with quota', async () => {
    const minter = authority; // use authority as minter for test
    const sig = await stable.updateMinter({
      minter: minter.publicKey,
      quota: 1_000_000_000n, // 1000 TUSD
      active: true,
    });
    expect(sig).to.be.a('string');
  });

  it('SSS-1: mint → getTotalSupply increases', async () => {
    const before = await stable.getTotalSupply();
    const sig = await stable.mint({
      recipient: authority.publicKey,
      amount: 500_000_000n, // 500 TUSD
    });
    expect(sig).to.be.a('string');
    const after = await stable.getTotalSupply();
    expect(after).to.be.greaterThan(before);
  });

  it('SSS-1: pause blocks minting', async () => {
    await stable.pause();
    const status = await stable.getStatus();
    expect(status.paused).to.be.true;

    try {
      await stable.mint({ recipient: authority.publicKey, amount: 1n });
      expect.fail('Should have thrown');
    } catch (e: any) {
      expect(e.message).to.include('Paused');
    }

    await stable.unpause();
    const statusAfter = await stable.getStatus();
    expect(statusAfter.paused).to.be.false;
  });

  it('SSS-1: freeze and thaw token account', async () => {
    const { getAssociatedTokenAddress, TOKEN_2022_PROGRAM_ID } = await import('@solana/spl-token');
    const ata = await getAssociatedTokenAddress(stable.mint, authority.publicKey, false, TOKEN_2022_PROGRAM_ID);
    const freezeSig = await stable.freeze(ata);
    expect(freezeSig).to.be.a('string');
    const thawSig = await stable.thaw(ata);
    expect(thawSig).to.be.a('string');
  });
});
